export enum CalendarType {
  LIGHT_DAY = "LIGHT_DAY",
  LIGHTEST_DAY = "LIGHTEST_DAY",
  MENS_EXPECTED = "MENS_EXPECTED",
  NEUTRAL = "NEUTRAL",
  NORMAL_DAY = "NORMAL_DAY",
  OVULATION_DAY_CALCULATED = "OVULATION_DAY_CALCULATED",
  OVULATION_DAY_FELT = "OVULATION_DAY_FELT",
  STRONG_DAY = "STRONG_DAY",
}
